CREATE DATABASE IF NOT EXISTS uvpredialdbdev;

USE uvpredialdbdev;

CREATE TABLE OWNER(
ID INT(8) NOT NULL PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(30) NOT NULL,
FIRST_SURNAME VARCHAR(30) NOT NULL,
SECOND_SURNAME VARCHAR(30) DEFAULT NULL,
SEX ENUM('MALE','FEMALE') NOT NULL,
MARITAL_STATUS ENUM('UNMARRIED','MARRIED') NOT NULL,
BIRTHDATE DATE NOT NULL,
BIRTHPLACE VARCHAR(50) NOT NULL,
PHONE_NUMBER VARCHAR(10) NOT NULL,
EMAIL VARCHAR(50) DEFAULT NULL,
CREATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFICATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE OWNER AUTO_INCREMENT=10000000;

CREATE TABLE ESTATE(
CFN INT(8) NOT NULL PRIMARY KEY COMMENT 'CADASTRAL FILE NUMBER',
TYPE VARCHAR(1) NOT NULL COMMENT 'PART OF THE CADASTRAL COMPOUND KEY',
LOCALITY VARCHAR(3) NOT NULL COMMENT 'PART OF THE CADASTRAL COMPOUND KEY',
REGION VARCHAR(2) NOT NULL COMMENT 'PART OF THE CADASTRAL COMPOUND KEY',
BLOCK VARCHAR(3) NOT NULL COMMENT 'PART OF THE CADASTRAL COMPOUND KEY',
LOT VARCHAR(3) NOT NULL COMMENT 'PART OF THE CADASTRAL COMPOUND KEY',
LEVEL VARCHAR(2) NOT NULL COMMENT 'PART OF THE CADASTRAL COMPOUND KEY',
DEPARTMENT VARCHAR(3) NOT NULL COMMENT 'PART OF THE CADASTRAL COMPOUND KEY',
SUBURB_NAME VARCHAR(50) NOT NULL,
STREET_NAME VARCHAR(50) NOT NULL,
STREET_NUMBER VARCHAR(10) NOT NULL,
APARTMENT_NUMBER VARCHAR(10) NOT NULL,
CREATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFICATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
OWNER_ID INT(8) NOT NULL,
FOREIGN KEY (OWNER_ID) REFERENCES OWNER(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE DEBT(
CTC INT(7) NOT NULL PRIMARY KEY COMMENT 'CADASTRAL TAX CODE',
DEBT_DATE DATE NOT NULL,
INITIAL_TAX DECIMAL(8,2) NOT NULL,
MONTHLY_INTEREST FLOAT(5,2) NOT NULL,
TOTAL_INTEREST FLOAT(5,2) NOT NULL,
TOTAL_TAX DECIMAL(8,2) NOT NULL,
PAYMENT_STATUS ENUM('PENDING','LIQUIDATED') NOT NULL DEFAULT 'PENDING',
CREATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFICATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CFN_ESTATE INT(8) NOT NULL COMMENT 'CADASTRAL FILE NUMBER',
FOREIGN KEY (CFN_ESTATE) REFERENCES ESTATE(CFN) ON UPDATE CASCADE ON DELETE RESTRICT
);
